apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo-eks
  region: us-west-1
  version: "1.18"
nodeGroups:
- amiFamily: AmazonLinux2
  desiredCapacity: 1
  iam:
    withAddonPolicies:
      autoScaler: true
      imageBuilder: true
  instanceType: t3.xlarge
  maxSize: 1
  minSize: 1
  name: ng-1
  volumeSize: 70
  volumeType: gp3
  privateNetworking: true
vpc:
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: false
  nat:
    gateway: Single
  subnets:
      private:
        us-west-1b:
          id: subnet-0bf6296c652a5
        us-west-1c:
          id: subnet-0e7ba2d2d4f35
      public:
        us-west-1b:
          id: subnet-0a52c40d9388a
        us-west-1c:
          id: subnet-0df8a7ec71f92